name: Build binaries and Release (arm64)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install npm dependencies
        run: npm install --omit=dev

      - name: Install pkg
        run: npm install -g pkg

      - name: Build
        run: npm run build:arm64

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ env.RELEASE_VERSION }}
